import React from 'react';
import { Plus, Flame, Timer, Activity } from 'lucide-react';
import { WorkoutLog, UserStats } from '../../types';

interface HomeViewProps {
  stats: UserStats;
  logs: WorkoutLog[];
  onCheckIn: () => void;
}

const HomeView: React.FC<HomeViewProps> = ({ stats, logs, onCheckIn }) => {
  const latestLog = logs.length > 0 ? logs[0] : null;

  return (
    <div className="p-6 pb-24 space-y-6 overflow-y-auto h-full no-scrollbar">
      {/* Header */}
      <div className="flex justify-between items-center pt-2">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">你好, 运动家 👋</h1>
          <p className="text-gray-500 text-sm mt-0.5">今天准备好流汗了吗？</p>
        </div>
        <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center text-indigo-600 font-bold border-2 border-white shadow-sm">
          FP
        </div>
      </div>

      {/* Main Stats Card */}
      <div className="bg-gradient-to-br from-indigo-600 to-violet-700 rounded-3xl p-6 text-white shadow-xl shadow-indigo-200 relative overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -mr-10 -mt-10 blur-2xl"></div>
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-black/10 rounded-full -ml-5 -mb-5 blur-xl"></div>
        
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-4">
            <div className="p-1.5 bg-white/20 rounded-lg">
               <Flame size={18} className="text-orange-300 fill-orange-300" />
            </div>
            <span className="font-medium text-indigo-100">当前连续打卡</span>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-5xl font-bold tracking-tight">{stats.currentStreak}</span>
            <span className="text-lg text-indigo-200">天</span>
          </div>
          <p className="mt-4 text-sm text-indigo-100/80">
            {stats.currentStreak > 0 
              ? "太棒了！保持这个节奏！" 
              : "开始你的连胜纪录吧！"}
          </p>
        </div>
      </div>

      {/* Quick Stats Grid */}
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
          <div className="flex items-center gap-2 text-gray-500 mb-2">
            <Activity size={16} />
            <span className="text-xs font-medium">总次数</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">{stats.totalWorkouts}</p>
        </div>
        <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100">
          <div className="flex items-center gap-2 text-gray-500 mb-2">
            <Timer size={16} />
            <span className="text-xs font-medium">总时长(分)</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">{stats.totalMinutes}</p>
        </div>
      </div>

      {/* Latest Activity / AI Motivation */}
      {latestLog && (
        <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
          <div className="flex justify-between items-start mb-3">
             <h3 className="font-bold text-gray-800">上次打卡鼓励</h3>
             <span className="text-xs text-gray-400">{latestLog.date}</span>
          </div>
          <div className="bg-orange-50 rounded-xl p-4 border border-orange-100">
            <p className="text-orange-800 text-sm font-medium leading-relaxed">
              " {latestLog.aiMotivation || "做的不错！继续加油！"} "
            </p>
            <div className="mt-2 flex items-center justify-end gap-1 text-xs text-orange-400">
               <span>Generated by Gemini</span>
               <div className="w-1.5 h-1.5 bg-orange-400 rounded-full animate-pulse"></div>
            </div>
          </div>
        </div>
      )}

      {/* FAB (Floating Action Button) for Mobile Feel */}
      <button 
        onClick={onCheckIn}
        className="fixed bottom-24 right-6 md:absolute md:bottom-24 md:right-6 bg-gray-900 text-white w-14 h-14 rounded-full flex items-center justify-center shadow-lg shadow-gray-400/50 hover:bg-black transition-transform active:scale-90 z-40"
      >
        <Plus size={28} />
      </button>
    </div>
  );
};

export default HomeView;